theory:
  cl_like.CCL:
    transfer_function: boltzmann_camb
    matter_pk: halofit
    baryons_pk: nobaryons
likelihood:
  cl_like.ClLike:
    input_file: /users/boryanah/repos/xCell-likelihoods/simple_marginalization/data/cls_covG_lsst.fits
    bins:
    - name: DESgc__0
    - name: DESgc__1
    - name: DESgc__2
    - name: DESgc__3
    - name: DESgc__4
    - name: DESwl__0
    - name: DESwl__1
    - name: DESwl__2
    - name: DESwl__3
    twopoints:
    - bins:
      - DESgc__0
      - DESgc__0
    - bins:
      - DESgc__1
      - DESgc__1
    - bins:
      - DESgc__2
      - DESgc__2
    - bins:
      - DESgc__3
      - DESgc__3
    - bins:
      - DESgc__4
      - DESgc__4
    - bins:
      - DESgc__0
      - DESwl__0
    - bins:
      - DESgc__0
      - DESwl__1
    - bins:
      - DESgc__0
      - DESwl__2
    - bins:
      - DESgc__0
      - DESwl__3
    - bins:
      - DESgc__1
      - DESwl__0
    - bins:
      - DESgc__1
      - DESwl__1
    - bins:
      - DESgc__1
      - DESwl__2
    - bins:
      - DESgc__1
      - DESwl__3
    - bins:
      - DESgc__2
      - DESwl__0
    - bins:
      - DESgc__2
      - DESwl__1
    - bins:
      - DESgc__2
      - DESwl__2
    - bins:
      - DESgc__2
      - DESwl__3
    - bins:
      - DESgc__3
      - DESwl__0
    - bins:
      - DESgc__3
      - DESwl__1
    - bins:
      - DESgc__3
      - DESwl__2
    - bins:
      - DESgc__3
      - DESwl__3
    - bins:
      - DESgc__4
      - DESwl__0
    - bins:
      - DESgc__4
      - DESwl__1
    - bins:
      - DESgc__4
      - DESwl__2
    - bins:
      - DESgc__4
      - DESwl__3
    - bins:
      - DESwl__0
      - DESwl__0
    - bins:
      - DESwl__0
      - DESwl__1
    - bins:
      - DESwl__0
      - DESwl__2
    - bins:
      - DESwl__0
      - DESwl__3
    - bins:
      - DESwl__1
      - DESwl__1
    - bins:
      - DESwl__1
      - DESwl__2
    - bins:
      - DESwl__1
      - DESwl__3
    - bins:
      - DESwl__2
      - DESwl__2
    - bins:
      - DESwl__2
      - DESwl__3
    - bins:
      - DESwl__3
      - DESwl__3
    defaults:
      kmax: 0.15
      lmin: 0
      lmax: 2000
      DESwl__0:
        lmin: 30
      DESwl__1:
        lmin: 30
      DESwl__2:
        lmin: 30
      DESwl__3:
        lmin: 30
    input_params_prefix: clk
    ia_model: IADESY1
    nz_model: NzShift
    shape_model: ShapeMultiplicative
    bias_model: Linear
params:
  A_sE9:
    prior:
      min: 0.5
      max: 5.0
    ref:
      dist: norm
      loc: 2.083
      scale: 0.1
    latex: A_s
    proposal: 0.0000001
  Omega_c:
    prior:
      min: 0.07
      max: 0.83
    ref:
      dist: norm
      loc: 0.26447041034523616
      scale: 0.1
    latex: \Omega_c
    proposal: 0.0000001
  Omega_b:
    prior:
      min: 0.03
      max: 0.07
    ref:
      dist: norm
      loc: 0.049301692328524445
      scale: 0.01
    latex: \Omega_b
    proposal: 0.0000001
  h:
    prior:
      min: 0.55
      max: 0.91
    ref:
      dist: norm
      loc: 0.6736
      scale: 0.2
    latex: h
    proposal: 0.0000001
  n_s:
    prior:
      min: 0.87
      max: 1.07
    ref:
      dist: norm
      loc: 0.9649
      scale: 0.2
    latex: n_s
    proposal: 0.0000001
  m_nu: 0.0
  sigma8:
    latex: \sigma_8
  clk_DESgc__0_b1:
    prior:
      min: 0.8
      max: 3.0
    ref:
      dist: norm
      loc: 1.421521
      scale: 0.0001
    latex: b^{DESgc}_0
    proposal: 0.0000001
  clk_DESgc__1_b1:
    prior:
      min: 0.8
      max: 3.0
    ref:
      dist: norm
      loc: 1.730038
      scale: 0.0001
    latex: b^{DESgc}_1
    proposal: 0.0000001
  clk_DESgc__2_b1:
    prior:
      min: 0.8
      max: 3.0
    ref:
      dist: norm
      loc: 1.699162
      scale: 0.0001
    latex: b^{DESgc}_2
    proposal: 0.0000001
  clk_DESgc__3_b1:
    prior:
      min: 0.8
      max: 3.0
    ref:
      dist: norm
      loc: 2.064552
      scale: 0.0001
    latex: b^{DESgc}_3
    proposal: 0.0000001
  clk_DESgc__4_b1:
    prior:
      min: 0.8
      max: 3.0
    ref:
      dist: norm
      loc: 2.129857
      scale: 0.0001
    latex: b^{DESgc}_4
    proposal: 0.0000001
  clk_DESgc__0_dz:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.07
    latex: \Delta z^{DESgc}_0
    proposal: 0.0000001
  clk_DESgc__1_dz:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.07
    latex: \Delta z^{DESgc}_1
    proposal: 0.0000001
  clk_DESgc__2_dz:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.06
    latex: \Delta z^{DESgc}_2
    proposal: 0.0000001
  clk_DESgc__3_dz:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.1
    latex: \Delta z^{DESgc}_3
    proposal: 0.0000001
  clk_DESgc__4_dz:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.1
    latex: \Delta z^{DESgc}_4
    proposal: 0.0000001
  clk_DESwl__0_m: 0.012
  clk_DESwl__1_m: 0.012
  clk_DESwl__2_m: 0.012
  clk_DESwl__3_m: 0.012
  clk_DESwl__0_dz:
    prior:
      dist: norm
      loc: -0.001
      scale: 0.16
    latex: \Delta z^{DESwl}_0
    proposal: 0.0000001
  clk_DESwl__1_dz:
    prior:
      dist: norm
      loc: -0.019
      scale: 0.13
    latex: \Delta z^{DESwl}_1
    proposal: 0.0000001
  clk_DESwl__2_dz:
    prior:
      dist: norm
      loc: 0.009
      scale: 0.11
    latex: \Delta z^{DESwl}_2
    proposal: 0.0000001
  clk_DESwl__3_dz:
    prior:
      dist: norm
      loc: -0.018
      scale: 0.22
    latex: \Delta z^{DESwl}_3
    proposal: 0.0000001
  clk_A_IA: 0.0
  clk_eta_IA: 0.0

sampler:
  mcmc:
    burn_in: 10
    max_tries: 20000
    learn_proposal: True
    Rminus1_stop: 0.01
    measure_speeds: True
    oversample_power: 1
    drag: True
    covmat: chains/lsst_3x2pt_dz.covmat
output: chains/lsst_3x2pt_dz_new
